import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { client } from '../contentful';
import styles from '../styles/Home.module.css';

const Home: NextPage = ({ main }: { main: any }) => {
  console.log(main);
  return (
    <div>
      <Head>
        <title>{main.fields.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{main.fields.title}</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const main = await client.getEntries({
    content_type: 'main',
    limit: 1,
  });

  const [mainPage] = main.items;

  return {
    props: {
      title: 'Мой Блог',
      main: mainPage,
    },
    revalidate: 3000,
  };
};
