import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { IArticle, IArticleFields, IMain, IMainFields } from '../contentful';
import { client } from '../contentful/index';
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import styles from '../styles/Home.module.css';
import {
  Container,
  Row,
  Col,
  Card,
  CardTitle,
  CardText,
  Button,
} from 'reactstrap';
import React from 'react';

export default function Home({
  main,
  articles,
}: {
  main: IMain;
  articles: IArticle[];
}) {
  // console.log(main);
  // console.log(articles);
  return (
    <div>
      <Head>
        <title>{main.fields.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className="text-center p-5 text-white"
          style={{
            background: `url("${main.fields.background?.fields.file.url}") no-repeat center / cover`,
            width: '100vw',
          }}
        >
          <h1 className="mt-5">{main.fields.title}</h1>
          {/* <div>{main.fields.description}</div> */}
          <div className="mb-5">
            {documentToReactComponents(main.fields.description!)}
          </div>
        </div>
        <Container className="pt-5">
          <Row>
            {articles.map((article) => {
              return (
                <Col sm={4} key={article.fields.slug}>
                  <Card>
                    <CardTitle tag="h5">{article.fields.title}</CardTitle>
                    <CardText>{article.fields.description}</CardText>
                    <Link href={`/articles/${article.fields.slug}`}>
                      <Button>{article.fields.action}</Button>
                    </Link>
                  </Card>
                </Col>
              );
            })}
          </Row>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const main = await client.getEntries<IMainFields>({
    content_type: 'main',
    limit: 1,
  });

  const articleEntries = await client.getEntries<IArticleFields>({
    content_type: 'article',
    select: 'fields.title,fields.slug,fields.description,fields.action', //обязательно без пробелов
    // limit: 1,
  });

  const [mainPage] = main.items;
  const articles = articleEntries.items;

  return {
    props: {
      // title: 'Мой Блог',
      main: mainPage,
      articles,
    },
    revalidate: 3000,
  };
};
